---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
vetorExample <- c(2, 6, 7)
listExample <- list(2, 6, 7)

print(vetorExample)
print(listExample)
```

```{r}
#用vector
c("2020-03-31T13:40:55Z",
  "一芳",
  "2",
  "水果茶")

#用list
library(lubridate)
`小明交易1` <- list(
  ymd_hms("2020-03-31T13:40:55Z"), # Date/Time class
  "一芳", # character
  2, # numeric
  "水果茶" # character
)
print(`小明交易1`)
```

```{r}
c(c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲"))

```

```{r}
# list含兩個vectors
`小明108學年課表A` <- list(
  c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲")
)
print(`小明108學年課表A`)
```

```{r}
# list含兩個lists
`小明108學年課表B` <- list(
  list("108-1","高級會計學","高等統計學"),
  list("108-2","食在拉丁美洲")
)
print(`小明108學年課表A`)
```

```{r}
# list含兩個lists, 子層list又各含兩個vectors
`小明108學年課表C` <- list(
  `上學期`=list(
    semester=c("108-1"), # 可只寫 "108-1"
    courses=c("高級會計學","高等統計學")
       ),
  `下學期`=list(
    semester=c("108-2"),
    courses=c("食在拉丁美洲")
  )
)
print(`小明108學年課表C`)
```


## Github Commit
```{r}
commit <- list(
  author = list(
    name="Martin老師",
    email="mtlin@gm.mtpu.edu.tw",
    time=ymd_hms("2020-03-25T07:17:20Z")),
  committer = list(
    name="emilyluckey",
    email="emily007@gmail.com",
    time=ymd_hms("2020-03-26T08:18:40Z")
  ),
  message = "update"
)
print(commit)
```


```{r}
library(jsonlite)
toJSON(commit)
```


```{r}
# 108-1 
course1_1081 <- 
  list(
    name="個體經濟學",
    teacher="Alice",
    grade=85
  )
course2_1081 <-
  list(
    name="總體經濟學",
    teacher="Mark",
    grade=78
  )
`108-1修課記錄` <- 
  list(
    course1_1081,
    course2_1081
  )

# 108-2
course1_1082 <- 
  list(
    name="作業研究",
    teacher="Jason",
    grade=90
  )
`108-2修課記錄` <- 
  list(
    course1_1082
  )

# 整合兩學期
`每學期修課記錄` <- list(
  `108-1`=`108-1修課記錄`,
  `108-2`=`108-2修課記錄`
)

# 完成記錄
`小明的修課記錄` <- 
  list(
    name="小明",
    semesters=`每學期修課記錄`
  )
```

##Weather
```{r}
weather_taipei <- list(
  date=list(today=ymd("2020-03-31"),tomorrow=ymd("2020-04-01")),
  city="台北市",
  MaxT=25,
  MinT=18
)
weather_newtaipei <- list(
  date=list(today="2020-03-31",tomorrow="2020-04-01"),
  city="新北市",
  MaxT=24,
  MinT=15
)
print(weather_taipei)
print(weather_newtaipei)
```


```{r}
Prisoners_dilemma <- list(
  `A_stays_silent`=list(
    `B_stays_silent`=list(A=-1,B=-1),
    `B_betrays`=list(A=-3,B=0)),
  `A_betrays`=list(
    `B_stays_silent`=list(A=0,B=-3),
    `B_betrays`=list(A=-2,B=-2))
)
Prisoners_dilemma
```

##Weather
```{r}
weather_forecast <- list(
  date=list(
    today=ymd("2020-03-31"),
    tomorrow=ymd("2020-04-01")),
  city="台北市",
  MaxT=25,
  MinT=18,
  date=list(
    today=ymd("2020-03-31"),
    tomorrow=ymd("2020-04-01")),
  city="新北市",
  MaxT=24,
  MinT=15
)

weather_forecast
```


