---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#新增/替換/刪除元素

```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在: 替換
a[[4]] <- "7" # 元素不存在： 增加
a[c(5,6)] <- c("J", "K")
a[[7]] <- "Johnson"
a <- c(a,"Mary")
a
```

```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    )
  )

str(list1)
```

```{r}
# 更改日期
list1[[1]]$birthday <- ymd("1997-03-21")

# 新增資料
list1[[2]] <- list(
  name="Mary",
  birthday=ymd("1998-08-24")
)

str(list1)
```

```{r}
list1[[1]][["age"]] <- 21
list1[[2]]["age"] <- list(21)

# 改變「一個」時，使用[[ ]]比較不會錯。
str(list1)
```

```{r}
list1[[1]][c("bloodType","registered")] <- list("AB",TRUE)

str(list1)
```

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
```

```{r}


# 108-1新增一科目成績
listExample[["學期"]]$`108-1`[[2]] <-
  list(name="產業經濟學")


listExample$學期$`108-1`[[2]][c("teacher","grade")] <- 
  list(
    "Wen",
    88
    )
str(listExample)

```

#刪除
```{r}
print(a)
a[-c(1,3)]
a[c(-2)]

print(a)
a[-c(1,3)] -> a # 要回存才算真的刪除
```

```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    ),
    list(
      name="Mary",
      birthday=ymd("1998-08-24"),
      status=c(height=163, weight=45),
      age=21,
      bloodType="AB"
    )
  )
str(list1)
```

```{r}
list1[[1]][-c(3)] -> list1[[1]]
list1[[2]][-c(3,5)] -> list1[[2]]
list1[[2]][c(3,5)] <- NULL

str(list1)
```

#練習
```{r}
library(jsonlite)
fromJSON("https://data.ntpc.gov.tw/od/data/api/54DDDC93-589C-4858-9C95-18B2046CC1FC?$format=json", simplifyDataFrame = F) -> newTaipeiYouBike
```

```{r}
#方法一
newTaipeiYouBike[[9]][-c(2)] -> newTaipeiYouBike[[9]]
str(newTaipeiYouBike[[9]])

#方法二
newTaipeiYouBike[[10]][c(2)] <- NULL
str(newTaipeiYouBike[[10]])
```

