---
---
```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```


```{r}
str(example[c("name","height")])

pick_above170 <- example$height >= 170
example$name[pick_above170]
```


```{r}
source("https://www.dropbox.com/s/qsrw069n94k61lj/transcript100to103_list.R?dl=1")
```


```{r}
# 只要成績大於85的
pick_above85 <-
  transcript100to103$`成績` > 85
```


```{r}
print(example[c("name","birthday")])

pick_after98 <- example$birthday >= lubridate::ymd("1998-01-01")
example$name[pick_after98]
```

```{r}
source("https://www.dropbox.com/s/16h6ggua6qtydci/exchangeRate.R?dl=1")
```

```{r}
str(exchangeRate)
```


```{r}
# 只要1998年1月（含）以後的
library(lubridate)
pick_after98_01 <-
  exchangeRate$`期間` >= lubridate::ymd("1998-01-01")
```

```{r}
exchangeRate_after98 <-
  list(
    `期間`=exchangeRate$`期間`[pick_after98_01],
    `幣別`=exchangeRate$`幣別`[pick_after98_01],
    `匯率`=exchangeRate$`匯率`[pick_after98_01]
  )
str(exchangeRate_after98)
```

```{r}
print(example[c("name","allowance")])

pick_allowanceOver1000 <- example$allowance >= "1001-2000"
example$name[pick_allowanceOver1000]
```

```{r}
example$allowance <- 
  ordered(example$allowance) #如果level順序是你要的
```

```{r}
example$allowance <-
  factor(
    example$allowance,
    levels=c("0-1000", "1001-2000", "2000+"), #自行設定level
    ordered = T # 設定為可排序factor
  )
```

```{r}
pick_allowanceOver1000 <- example$allowance >= "1001-2000"
example$name[pick_allowanceOver1000]
```

```{r}
jsonlite::fromJSON("https://www.dropbox.com/s/3uijub7xheib405/list_victimAges_female.json?dl=1", simplifyDataFrame = F) -> list_victimAges_female
```

```{r}
list_victimAges_female$`數目` <-
  as.integer(list_victimAges_female$`數目`)
list_victimAges_female$`年齡層` <- 
  as.factor(list_victimAges_female$`年齡層`)
```

```{r}
sum(list_victimAges_female$`數目`, na.rm=T)
sum(list_victimAges_female$`數目`[pick_above30], na.rm = T)
```
```{r}
levels(list_victimAges_female$`年齡層`) -> levels_ages
print(levels_ages)
```

```{r}
levels_new <- c(levels_ages[c(12,13,1,8,2:7,9:11)])
levels(list_victimAges_female$`年齡層`) <- levels_new
print(levels_new)
```

```{r}
ordered(levels_new) -> list_victimAges_female$`年齡層`
```

```{r}
pick_above30 <- list_victimAges_female$`年齡層` >= "30_39歲"

```

